config/routes.rb
Rails.application.routes.draw do
  get 'evaluations/create'

  get 'evaluations/destroy'

  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'about', to: 'toppages#about'
  get 'signup', to: 'users#new'
  get 'rankings/like', to: 'rankings#like'
  get 'rankings/ramenpost', to: 'rankings#ramenpost'
  
  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get :followings
      get :followers
      get :likes
      get :evaluates
    end
    collection do
      get :search
    end
  end
 
  resources :ramenposts, only: [:create, :edit, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :evaluations, only: [:create, :destroy]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message|%>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_modal.html.erb
<p class="img-responsive thumbnail　aligncenter size-full wp-image-425 " data-toggle="modal" data-target="#image_Modal_<%= ramenpost.id %>" style="cursor:pointer; text-align:center">
 <%= image_tag ramenpost.image.thumb, class: "img-responsive", style: 'margin: auto;', size: '400' %> 
</p>
<div class="modal fade" id="image_Modal_<%= ramenpost.id %>" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg modal-middle"> 
   <div class="text-center">
    <p><%= ramenpost.restaurant_name %></p>
    <p class="aligncenter size-full wp-image-425"><%= image_tag ramenpost.image, class: "img-responsive img-center" %></p>
  　 <div class="modal-img_footer">
     <%= render 'likes/like_button', ramenpost: ramenpost %>
     <% if current_user == ramenpost.user %>
      <%= link_to "", ramenpost, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-primary btn-md glyphicon glyphicon-trash' %><br>
     <% end %>
      平均評価:<div id="average-<%= ramenpost.id %>" style="pointer-events:none;"></div><%= ave = Evaluation.where(ramenpost_id: ramenpost.id).average(:star).try!(:round, 2) %><br>
      あなたの評価:<% user_evaluation = Evaluation.find_by(user_id: current_user.id, ramenpost_id: ramenpost.id).try!(:star) %> 
      <%= form_tag evaluations_path, checked: user_evaluation, id: "ramenpost-form-#{ramenpost.id}" do %>
      <%= hidden_field_tag :ramenpost_id, ramenpost.id %>
      <div id="evaluation-<%= ramenpost.id %>"></div>
    　　 <%= submit_tag "評価する" %>
    　<% end %> 
      <span class="glyphicon glyphicon-cutlery"></span>：<%= ramenpost.menu %></br>
      <span class="glyphicon glyphicon-pencil"></span>：<%= ramenpost.content %></br>
    　<button type="button" class="btn btn-success" data-dismiss="modal">Close</button> 
    </div>
   </div>
  </div>
</div>

<script>
  $("#average-<%= ramenpost.id %>").raty({
      number: 5,
      score : <%= ave || 0 %>
  });
  $("#evaluation-<%= ramenpost.id %>").raty({
      number: 5,
      score : <%= user_evaluation || 0 %>
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Ramenposts</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>